version: '3.8'

services:
  web:
    build: ./web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_db

volumes:
  postgres_data: